/**
 * Code-drawn pixel-grid sprites for what the tilesets lack (fallback icons, landmarks, pylon).
 *
 * Legend: '.' transparent, 'o' outline, 'd' dark, 'b' base, 'l' light,
 * 'h' highlight, 's' stone/bone, 'a' accent (glow/lava/danger), 'w' white.
 */

import { Graphics } from 'pixi.js';
import { LandmarkGlyphKind, LocationType } from '../../../domain/map-types';
import { PixelChar, PixelSpritePalette } from './pixel-palette';

export const PIXEL_GRID_CHARS: ReadonlySet<string> = new Set(['.', 'o', 'd', 'b', 'l', 'h', 's', 'a', 'w']);

export function drawPixelGrid(
  g: Graphics,
  grid: string[],
  palette: PixelSpritePalette,
  originX = 0,
  originY = 0,
  pixelSize = 1,
  alpha = 1
): void {
  // Batch by palette character: one fill() per color keeps bake cost low
  const cellsByChar = new Map<PixelChar, Array<[number, number]>>();
  for (let y = 0; y < grid.length; y++) {
    const row = grid[y];
    for (let x = 0; x < row.length; x++) {
      const ch = row[x];
      if (ch === '.') continue;
      const list = cellsByChar.get(ch as PixelChar) ?? [];
      list.push([x, y]);
      cellsByChar.set(ch as PixelChar, list);
    }
  }
  for (const [ch, cells] of cellsByChar) {
    for (const [x, y] of cells) {
      g.rect(originX + x * pixelSize, originY + y * pixelSize, pixelSize, pixelSize);
    }
    g.fill({ color: palette[ch], alpha });
  }
}

export const LOCATION_ICONS: Record<LocationType, string[]> = {
  city: [
    '............',
    '..o......o..',
    '.obo....obo.',
    '.obo.oo.obo.',
    '.oboobboobo.',
    '.obbbbbbbbo.',
    '.oblbblbblo.',
    '.obbbbbbbbo.',
    '.obloobolbo.',
    '.obbo..obbo.',
    '.oooo..oooo.',
    '............',
  ],
  village: [
    '............',
    '.....oo.....',
    '....ollo....',
    '...ollllo...',
    '..ollllllo..',
    '.oooooooooo.',
    '..obbbbbbo..',
    '..obboobbo..',
    '..obbddbbo..',
    '..obbddbbo..',
    '..oooooooo..',
    '............',
  ],
  sect: [
    '.....oo.....',
    '....obbo....',
    '..oooooooo..',
    '.ollllllllo.',
    '...obbbbo...',
    '..oooooooo..',
    '.ollllllllo.',
    '...obddbo...',
    '...obddbo...',
    '..oooooooo..',
    '............',
    '............',
  ],
  clan: [
    '............',
    '..oooooooo..',
    '..obbbbbbo..',
    '..oblaalbo..',
    '..obaaaabo..',
    '..obllllbo..',
    '..obbbbbbo..',
    '...obbbbo...',
    '....obbo....',
    '.....oo.....',
    '............',
    '............',
  ],
  castle: [
    '............',
    '.o.o.oo.o.o.',
    '.oooooooooo.',
    '.obbbbbbbbo.',
    '.oblbbbblbo.',
    '.obbbbbbbbo.',
    '.obbboobbbo.',
    '.obbddddbbo.',
    '.obbddddbbo.',
    '.oooooooooo.',
    '............',
    '............',
  ],
  ruin: [
    '............',
    '..o.....o...',
    '.obo...obo..',
    '.obo...obo..',
    '.obo....o...',
    '.obo........',
    '.obo..o.....',
    '.obo.obo....',
    '.obo.obo.oo.',
    'ossssssssso.',
    'ooooooooooo.',
    '............',
  ],
  dungeon: [
    '............',
    '...oooooo...',
    '..osssssso..',
    '.ossddddsso.',
    '.osddddddso.',
    '.osdaddadso.',
    '.osddddddso.',
    '.osddddddso.',
    '.osddddddso.',
    '.oooooooooo.',
    '............',
    '............',
  ],
  mountain: [
    '............',
    '.....oo.....',
    '....ohho....',
    '...ohllbo...',
    '...olbbbo...',
    '..olbbbbbo..',
    '..obbbdbbo..',
    '.olbbddbbbo.',
    '.obbddddbbo.',
    'obbdddddddbo',
    'oooooooooooo',
    '............',
  ],
  cave: [
    '............',
    '............',
    '....oooo....',
    '..oossssoo..',
    '.osssssssso.',
    '.ossoddosso.',
    '.osoddddoso.',
    'osoddddddoso',
    'osoddddddoso',
    'oooooooooooo',
    '............',
    '............',
  ],
  battlefield: [
    '............',
    '.o........o.',
    '..o......o..',
    '...h....h...',
    '....h..h....',
    '.....hh.....',
    '.....hh.....',
    '....h..h....',
    '..oah..hao..',
    '..oo....oo..',
    '.o........o.',
    '............',
  ],
  temple: [
    '............',
    '.....oo.....',
    '....ollo....',
    '...ollllo...',
    '..oooooooo..',
    '..os.ss.so..',
    '..os.ss.so..',
    '..os.ss.so..',
    '..os.ss.so..',
    '.oooooooooo.',
    'osssssssssso',
    'oooooooooooo',
  ],
  ocean: [
    '............',
    '............',
    '............',
    '..oo....oo..',
    '.ollo..ollo.',
    'ob..lbbl..bo',
    '............',
    '..oo....oo..',
    '.ollo..ollo.',
    'ob..lbbl..bo',
    '............',
    '............',
  ],
  island: [
    '............',
    '...ooo.oo...',
    '..ollloollo.',
    '.ol..ol..lo.',
    '.....ol.....',
    '.....ol.....',
    '....ool.....',
    '...ossso....',
    '..ossssso...',
    '.obbbbbbbbo.',
    'obbbbbbbbbbo',
    '............',
  ],
  portal: [
    '....oooo....',
    '...oaaaao...',
    '..oa....ao..',
    '..oa.hh.ao..',
    '.oa.hllh.ao.',
    '.oa.hllh.ao.',
    '.oa.hllh.ao.',
    '.oa..hh..ao.',
    '.oa......ao.',
    '.oa......ao.',
    'oooo....oooo',
    '............',
  ],
  landmark: [
    '.....oo.....',
    '.....hh.....',
    '....ohho....',
    '....olbo....',
    '....olbo....',
    '....olbo....',
    '....olbo....',
    '...oolboo...',
    '...olbbbo...',
    '..oooooooo..',
    '..osssssso..',
    '..oooooooo..',
  ],
  lake: [
    '............',
    '............',
    '...oooooo...',
    '..obbbbbbo..',
    '.obblllbbbo.',
    '.oblhhllbbo.',
    '.obbllbbbbo.',
    '..obbbbbbo..',
    '...oooooo...',
    '............',
    '............',
    '............',
  ],
};

export const LANDMARK_SPRITES: Record<LandmarkGlyphKind, string[]> = {
  volcano: [
    '....aaa.....',
    '.....a......',
    '....oaao....',
    '...oddddo...',
    '...olbddo...',
    '..olbbbddo..',
    '..olbbbddo..',
    '.olbbbbdddo.',
    '.obbbbbdddo.',
    'olbbbbbddddo',
    'oooooooooooo',
    '............',
  ],
  spire: [
    '.....oo.....',
    '.....hh.....',
    '....ohlo....',
    '....olbo....',
    '....olbo....',
    '...oolbdo...',
    '...olbbdo...',
    '...olbbdo...',
    '..oolbbddo..',
    '..olbbbddo..',
    '.oooooooooo.',
    '............',
  ],
  ruin: [
    '............',
    '.o.......o..',
    'oso.....oso.',
    'oso.o...oso.',
    'oso.....oso.',
    'oso..o..oso.',
    'oso.oso.oso.',
    'oso.oso.oso.',
    'oso.oso.oso.',
    'ossssssssso.',
    'ooooooooooo.',
    '............',
  ],
  'great-tree': [
    '...oooooo...',
    '..olllllbo..',
    '.olllllbbbo.',
    'olllllbbbbbo',
    'olllbbbbbbdo',
    '.obbbbbbddo.',
    '..oobddboo..',
    '....oddo....',
    '....oddo....',
    '....oddo....',
    '...oddddo...',
    '..oooooooo..',
  ],
  citadel: [
    '..o..oo..o..',
    '.oho.oo.oho.',
    '.olo.oo.olo.',
    '.olooaaoolo.',
    '.olbbbbbblo.',
    '.olbllllblo.',
    '.olbbbbbblo.',
    '.olbbddbblo.',
    '.olbbddbblo.',
    'oooooooooooo',
    'osssssssssso',
    'oooooooooooo',
  ],
  crater: [
    '............',
    '............',
    '............',
    '...oooooo...',
    '.oollsslloo.',
    'olldddddddlo',
    'olddaaaaddlo',
    'olldddddddlo',
    '.oollsslloo.',
    '...oooooo...',
    '............',
    '............',
  ],
  monolith: [
    '....oooo....',
    '...ossdso...',
    '...osadso...',
    '...ossdso...',
    '...osadso...',
    '...ossdso...',
    '...ossdso...',
    '...osadso...',
    '...ossdso...',
    '..oossdsoo..',
    '.oooooooooo.',
    '............',
  ],
  shipwreck: [
    '............',
    '.....o......',
    '.....o.oo...',
    '....oo.o....',
    '...oso.o....',
    '..osso.o....',
    '.......o....',
    'oooooooooo..',
    'obbdbbdbbo..',
    '.obbbbbbo...',
    '..oooooo....',
    '............',
  ],
  'portal-arch': [
    '...oooooo...',
    '..osssssso..',
    '.osooooooso.',
    '.oso.aa.oso.',
    '.osoahhaoso.',
    '.osoahhaoso.',
    '.osoahhaoso.',
    '.oso.aa.oso.',
    '.oso....oso.',
    '.oso....oso.',
    'ooooo..ooooo',
    '............',
  ],
  'skull-rock': [
    '...oooooo...',
    '..osssssso..',
    '.osssssssso.',
    '.osddssddso.',
    '.osdassadso.',
    '.osddssddso.',
    '.osssddssso.',
    '..osssssso..',
    '..osososso..',
    '...oooooo...',
    '............',
    '............',
  ],
};

export const WAYPOINT_PYLON: string[] = [
  '...oo...',
  '..oaao..',
  '..oaao..',
  '...oo...',
  '..osso..',
  '..osso..',
  '..osso..',
  '.osssso.',
  'oooooooo',
];
